version: '3.2'
services:
  game:
    image: joshhsoj1902/linuxgsm-docker:local
    ports:
      - target: 27015
        published: 27015
        protocol: tcp
        mode: host
      - target: 27015
        published: 27015
        protocol: udp
        mode: host
      - target: 27020
        published: 27020
        protocol: udp
        mode: host
      - target: 27005
        published: 27005
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      - bind_gateway
      - bind_overlay=10.0.0.1
      - bind_ingress=10.255.0.1
      # - bind_gateway=10.255.0.1
      # - LGSM_GAMESERVERNAME=mumbleserver
      - LGSM_GAMESERVERNAME=cssserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE


