# This hasn't been tested, Setting the config is'nt overly clear https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/wetserver/_default.cfg
version: '3.1'
services:
  game:
    image: joshhsoj1902/linuxgsm-docker:latest
    # ports:
    #   - 10027:10027/tcp
    #   - 10027:10027/udp
    environment:
      - LGSM_GAMESERVERNAME=wetserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
    volumes:
      - "/home/linuxgsm/linuxgsm/logs"
