#############################
# SERVER STATUS
#############################
#
# Working: Unsure
# Tested in CI: Yes
#
# Does this server have save files: Unsure
# Where are save files saved: Unsure, somewhere in `serverfiles`
#
# Configuration:
#  - https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/wetserver/_default.cfg
#
############################

version: '3.3'
volumes:
  serverfiles:
services:
  wet:
    image: joshhsoj1902/linuxgsm-docker:latest
    # ports:
    #   - 10027:10027/tcp
    #   - 10027:10027/udp
    environment:
      - LGSM_GAMESERVERNAME=wetserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE

    # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
    volumes:
      - serverfiles:/home/linuxgsm/linuxgsm/serverfiles
