version: '3.1'
services:
  game:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      - LGSM_GAMESERVERNAME=l4d2server
      - LGSM_UPDATEINSTALLSKIP=UPDATE
      # - LGSM_DEFAULTMAP=gm_construct
      # - LGSM_GAMEMODE=sandbox
    volumes:
      - "/home/steam/linuxgsm/logs"
