version: '3.1'
services:
  game:
    image: joshhsoj1902/linuxgsm-docker:latest
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      - LGSM_GAMESERVERNAME=csgoserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
    volumes:
      - "/home/linuxgsm/linuxgsm/logs"
